export const ANNOUNCMENT_LIST_REQUEST = "ANNOUNCMENT_LIST_REQUEST";
export const ANNOUNCMENT_LIST_SUCCESS = "ANNOUNCMENT_LIST_SUCCESS";
export const ANNOUNCMENT_LIST_FAIL = "ANNOUNCMENT_LIST_FAIL";

export const ANNOUNCMENT_LIST_REQUEST_OWN = "ANNOUNCMENT_LIST_REQUEST_OWN";
export const ANNOUNCMENT_LIST_SUCCESS_OWN = "ANNOUNCMENT_LIST_SUCCESS_OWN";
export const ANNOUNCMENT_LIST_FAIL_OWN = "ANNOUNCMENT_LIST_FAIL_OWN";

export const ANNOUNCMENT_CREATE_REQUEST = "ANNOUNCMENT_CREATE_REQUEST";
export const ANNOUNCMENT_CREATE_SUCCESS = "ANNOUNCMENT_CREATE_SUCCESS";
export const ANNOUNCMENT_CREATE_FAIL = "ANNOUNCMENT_CREATE_FAIL";

export const ANNOUNCMENT_UPDATE_REQUEST = "ANNOUNCMENT_UPDATE_REQUEST";
export const ANNOUNCMENT_UPDATE_SUCCESS = "ANNOUNCMENT_UPDATE_SUCCESS";
export const ANNOUNCMENT_UPDATE_FAIL = "ANNOUNCMENT_UPDATE_FAIL";

export const ANNOUNCMENT_DELETE_REQUEST = "ANNOUNCMENT_DELETE_REQUEST";
export const ANNOUNCMENT_DELETE_SUCCESS = "ANNOUNCMENT_DELETE_SUCCESS";
export const ANNOUNCMENT_DELETE_FAIL = "ANNOUNCMENT_DELETE_FAIL";
