export const PUBLIC_NOTES_LIST_REQUEST = "PUBLIC_NOTES_LIST_REQUEST";
export const PUBLIC_NOTES_LIST_SUCCESS = "PUBLIC_NOTES_LIST_SUCCESS";
export const PUBLIC_NOTES_LIST_FAIL = "PUBLIC_NOTES_LIST_FAIL";

export const PUBLIC_NOTES_CREATE_REQUEST = "PUBLIC_NOTES_CREATE_REQUEST";
export const PUBLIC_NOTES_CREATE_SUCCESS = "PUBLIC_NOTES_CREATE_SUCCESS";
export const PUBLIC_NOTES_CREATE_FAIL = "PUBLIC_NOTES_CREATE_FAIL";

export const PUBLIC_NOTES_UPDATE_REQUEST = "PUBLIC_NOTES_UPDATE_REQUEST";
export const PUBLIC_NOTES_UPDATE_SUCCESS = "PUBLIC_NOTES_UPDATE_SUCCESS";
export const PUBLIC_NOTES_UPDATE_FAIL = "PUBLIC_NOTES_UPDATE_FAIL";

export const PUBLIC_NOTES_DELETE_REQUEST = "PUBLIC_NOTES_DELETE_REQUEST";
export const PUBLIC_NOTES_DELETE_SUCCESS = "PUBLIC_NOTES_DELETE_SUCCESS";
export const PUBLIC_NOTES_DELETE_FAIL = "PUBLIC_NOTES_DELETE_FAIL";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAIL = "USER_PROFILE_FAIL";
